= Install the OpenStack Operator

FIXME: numbering on the page

. Clone the Files Repo
+
In the bastion terminal, clone the repo and change directory to the files that we will used later in the lab
+
[source,bash,role=execute]
----
git clone https://github.com/pnavarro/showroom_osp-on-ocp-lb1374.git labrepo
cd labrepo/content/files
----

. Create required projects for the Openstack Operator installation.
+
The next installation step for the *OpenStack Operators* involves creating the *openstack-operators* and *openstack* projects for the RHOSO operators.
+
[source,bash,role=execute]
----
oc new-project openstack-operators
oc new-project openstack
----

. Prepare the secret for installating the operators:
+
Login with your Red Hat account and create a secret:
+
[source,bash,role=execute]
----
podman login --username "6340056|osp-on-ocp-lb1374" --password "eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiI1Y2EzM2NjNGY4NWM0MmZmYTI3YmU5Y2UyMWI3M2JjMCJ9.GAxgg6Ht2oCS8zxHdwQw9kSD6RHeQOWYaDOcnQB5RElewQKvZmcNWi-YJdInJ5iXTE9r9tGVIN7fhFJL7f-hhL1PK2RVzZHD8qyfkMWcCEF5GUvp8rDX4GDrSkqjpUD44teWYkOy9Nb-3pOGzRIC7qs88uSxMz7hfil4I_HmjF4AAPIi4j3QZhp0lqrXzzf7vt6NLlizDFa2XTcPf_vQqReFu3A_5iWfy8XmLlC7QIixeVv2IE-ahRqM_UDCf5Dg3n2WpYvmP5jcSPFOLoT7sMimyeaPBna793boiX2swmeGHQ23tx1nFavCUavGv_cDRAvzVXCJ2NROTJ5unHiN7CXEbzm4Rg-65tY4D0YynTU8L6t0gYtXYYY9_wi1xNs-cShAmCMh1ySJn9nBcq4ydvH7eQnhSEvoK0bPsN_vWJCgOQBQyOdpTfRMU6piAy9H1zJ0KzsSzuKSS8fX0m9oN7narZPl34DTiEUTDeW8_SS6vJjHr_Q9O_X4mVeeQhH2ocN_4M9R6A89tmQ2jObuWm-cu1Yk-G6FSPUONhsoC_99nQnICS4mAuCWWDHxFY61hIrreVZBSH053MgfSaG2sqTb26MkxKWx-TP1sx18pb1xmo4IQEwILIbLlSPA3vafbrbQO5RQcm3UYKtYwev0vAlL5taXiTuLEyPscdzv0Sc" registry.redhat.io --authfile auth.json
----
+
FIXME: Account details 

. Ensure that you observe the `Login Succeeded!` message in the output of the preceding command, then confirm the creation of the `auth.json` file.
[source,bash,role=execute]
----
cat auth.json
----

. Create secret for the registry:
+
[source,bash,role=execute]
----
oc create secret generic osp-operators-secret \
 -n openstack-operators \
 --from-file=.dockerconfigjson=auth.json \
 --type=kubernetes.io/dockerconfigjson
----
+
Veify the secret is created:
+
[source,bash,role=execute]
----
oc get secrets -n openstack-operators osp-operators-secret
----
+
.Sample Output
----
NAME                   TYPE                             DATA   AGE
osp-operators-secret   kubernetes.io/dockerconfigjson   1      10s
----

. Configure the **Catalog Source, OperatorGroup and Subscription** for the **OpenStack Operator** using your registry:
+
Create the new **CatalogSource, OperatorGroup, and Subscription** CRs in the **openstack** namespace from **files/openstack-operators.yaml**: You can cut and paste the referenced yamlfiles from the repo or you may wish to clone the repository onto the bastion which this guide will assume:
+
[source,bash,role=execute]
----
oc apply -f osp-ng-openstack-operator.yaml
----

. Confirm that you have installed the Openstack Operator, *openstack-operator.openstack-operators*:
+
[source,bash,role=execute]
----
oc get operators openstack-operator.openstack-operators
----

. Review the pods in the **openstack-operators** namespace:
+
[source,bash,role=execute]
----
oc get pods -n openstack-operators
----

. If you run:
+
[source, bash,role=execute]
----
oc get pods -n openstack-operators --sort-by=.metadata.creationTimestamp
----
+
You should see a list of completed pods and then the running openstack services pods.
It should look like:
+
.Sample Output
----
NAME                                                              READY   STATUS      RESTARTS   AGE
(...)
openstack-operator-index-89nv9                                    1/1     Running     0          7m30s

neutron-operator-controller-manager-5755996c4b-ctbf8              2/2     Running     0          7m19s
openstack-ansibleee-operator-controller-manager-6d7d77fc45pdtfj   2/2     Running     0          7m13s
openstack-operator-controller-manager-56fb74ccb7-r8lvn            2/2     Running     0          7m1s
dataplane-operator-controller-manager-6844bfd645-f2zvs            2/2     Running     0          7m1s
glance-operator-controller-manager-596b56cd5-rvfrm                2/2     Running     0          6m59s
swift-operator-controller-manager-df5fbbbc5-zscc5                 2/2     Running     0          6m49s
octavia-operator-controller-manager-6549bc8f-r6xbp                2/2     Running     0          6m42s
openstack-baremetal-operator-controller-manager-7cd655c4c7f5glm   2/2     Running     0          6m42s
barbican-operator-controller-manager-69b766c996-ldg4n             2/2     Running     0          6m28s
(...)
----
+
Wait to see all the `Running` pods in `READY` state.